// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/scan_job.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_INVALID     ResourceType = 0
	ResourceType_PLAYLIST_ID ResourceType = 1
	ResourceType_TRACK_ID    ResourceType = 2
	ResourceType_ALBUM_ID    ResourceType = 3
	ResourceType_ARTIST_ID   ResourceType = 4
	ResourceType_ARTIST_NAME ResourceType = 5
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "INVALID",
		1: "PLAYLIST_ID",
		2: "TRACK_ID",
		3: "ALBUM_ID",
		4: "ARTIST_ID",
		5: "ARTIST_NAME",
	}
	ResourceType_value = map[string]int32{
		"INVALID":     0,
		"PLAYLIST_ID": 1,
		"TRACK_ID":    2,
		"ALBUM_ID":    3,
		"ARTIST_ID":   4,
		"ARTIST_NAME": 5,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scan_job_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_proto_scan_job_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{0}
}

type ContentFetchJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,3,opt,name=resource_type,json=resourceType,proto3,enum=ruscan.ResourceType" json:"resource_type,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentFetchJob) Reset() {
	*x = ContentFetchJob{}
	mi := &file_proto_scan_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentFetchJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentFetchJob) ProtoMessage() {}

func (x *ContentFetchJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scan_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentFetchJob.ProtoReflect.Descriptor instead.
func (*ContentFetchJob) Descriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{0}
}

func (x *ContentFetchJob) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentFetchJob) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ContentFetchJob) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_INVALID
}

func (x *ContentFetchJob) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type ArtistRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtistRef) Reset() {
	*x = ArtistRef{}
	mi := &file_proto_scan_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtistRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtistRef) ProtoMessage() {}

func (x *ArtistRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scan_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtistRef.ProtoReflect.Descriptor instead.
func (*ArtistRef) Descriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{1}
}

func (x *ArtistRef) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ArtistRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Artists       []*ArtistRef           `protobuf:"bytes,4,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_proto_scan_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scan_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{2}
}

func (x *Track) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Track) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Track) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Track) GetArtists() []*ArtistRef {
	if x != nil {
		return x.Artists
	}
	return nil
}

type ContentScanJob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScanJobId     string                 `protobuf:"bytes,1,opt,name=scan_job_id,json=scanJobId,proto3" json:"scan_job_id,omitempty"`
	Tracks        []*Track               `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	Artists       []*ArtistRef           `protobuf:"bytes,3,rep,name=artists,proto3" json:"artists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentScanJob) Reset() {
	*x = ContentScanJob{}
	mi := &file_proto_scan_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentScanJob) ProtoMessage() {}

func (x *ContentScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scan_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentScanJob.ProtoReflect.Descriptor instead.
func (*ContentScanJob) Descriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{3}
}

func (x *ContentScanJob) GetScanJobId() string {
	if x != nil {
		return x.ScanJobId
	}
	return ""
}

func (x *ContentScanJob) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

func (x *ContentScanJob) GetArtists() []*ArtistRef {
	if x != nil {
		return x.Artists
	}
	return nil
}

var File_proto_scan_job_proto protoreflect.FileDescriptor

const file_proto_scan_job_proto_rawDesc = "" +
	"\n" +
	"\x14proto/scan_job.proto\x12\x06ruscan\"\x96\x01\n" +
	"\x0fContentFetchJob\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\rresource_type\x18\x03 \x01(\x0e2\x14.ruscan.ResourceTypeR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\"@\n" +
	"\tArtistRef\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x86\x01\n" +
	"\x05Track\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl\x12+\n" +
	"\aartists\x18\x04 \x03(\v2\x11.ruscan.ArtistRefR\aartists\"\x84\x01\n" +
	"\x0eContentScanJob\x12\x1e\n" +
	"\vscan_job_id\x18\x01 \x01(\tR\tscanJobId\x12%\n" +
	"\x06tracks\x18\x02 \x03(\v2\r.ruscan.TrackR\x06tracks\x12+\n" +
	"\aartists\x18\x03 \x03(\v2\x11.ruscan.ArtistRefR\aartists*h\n" +
	"\fResourceType\x12\v\n" +
	"\aINVALID\x10\x00\x12\x0f\n" +
	"\vPLAYLIST_ID\x10\x01\x12\f\n" +
	"\bTRACK_ID\x10\x02\x12\f\n" +
	"\bALBUM_ID\x10\x03\x12\r\n" +
	"\tARTIST_ID\x10\x04\x12\x0f\n" +
	"\vARTIST_NAME\x10\x05B\x17Z\x15internal/shared/queueb\x06proto3"

var (
	file_proto_scan_job_proto_rawDescOnce sync.Once
	file_proto_scan_job_proto_rawDescData []byte
)

func file_proto_scan_job_proto_rawDescGZIP() []byte {
	file_proto_scan_job_proto_rawDescOnce.Do(func() {
		file_proto_scan_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scan_job_proto_rawDesc), len(file_proto_scan_job_proto_rawDesc)))
	})
	return file_proto_scan_job_proto_rawDescData
}

var file_proto_scan_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scan_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_scan_job_proto_goTypes = []any{
	(ResourceType)(0),       // 0: ruscan.ResourceType
	(*ContentFetchJob)(nil), // 1: ruscan.ContentFetchJob
	(*ArtistRef)(nil),       // 2: ruscan.ArtistRef
	(*Track)(nil),           // 3: ruscan.Track
	(*ContentScanJob)(nil),  // 4: ruscan.ContentScanJob
}
var file_proto_scan_job_proto_depIdxs = []int32{
	0, // 0: ruscan.ContentFetchJob.resource_type:type_name -> ruscan.ResourceType
	2, // 1: ruscan.Track.artists:type_name -> ruscan.ArtistRef
	3, // 2: ruscan.ContentScanJob.tracks:type_name -> ruscan.Track
	2, // 3: ruscan.ContentScanJob.artists:type_name -> ruscan.ArtistRef
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_scan_job_proto_init() }
func file_proto_scan_job_proto_init() {
	if File_proto_scan_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scan_job_proto_rawDesc), len(file_proto_scan_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scan_job_proto_goTypes,
		DependencyIndexes: file_proto_scan_job_proto_depIdxs,
		EnumInfos:         file_proto_scan_job_proto_enumTypes,
		MessageInfos:      file_proto_scan_job_proto_msgTypes,
	}.Build()
	File_proto_scan_job_proto = out.File
	file_proto_scan_job_proto_goTypes = nil
	file_proto_scan_job_proto_depIdxs = nil
}
