services:
  api:
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile.api
    volumes:
      - ./backend:/build
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/app?sslmode=disable
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  spotify-gateway:
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile.spotify-gateway
    environment:
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672/
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/build
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  scan-worker:
    restart: unless-stopped
    build:
      context: ./backend
      target: dev
      dockerfile: Dockerfile.scan-worker
    volumes:
      - ./backend:/build
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/app?sslmode=disable
      - RABBITMQ_URL=amqp://app:app@rabbitmq:5672
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  scraper:  
    profiles:
    - scraper
    build:
      context: ./backend
      dockerfile: Dockerfile.scraper
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgres://app:app@postgres:5432/app?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - SCRAPE_LASTFM_TOP_ARTISTS_FOR_ALL_TAGS=true
      - SCRAPE_MUSICBRAINZ_ARTISTS_FOR_ALL_REGIONS=true
      - SCRAPE_PHONKERS_DB_ARTISTS=true
    depends_on:
      api:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://api:8080
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy


  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  postgres_data:
  frontend_node_modules: