FROM golang:1.26.2-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app ./cmd/scraper

# Prod
FROM gcr.io/distroless/static:nonroot 
COPY --from=builder /app /app
ENTRYPOINT ["/app"]
