# Dev with hot reload
FROM golang:1.26.2-alpine AS dev
WORKDIR /build
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download
CMD ["air", "--build.cmd", "go build -o ./tmp/main ./cmd/api", "--build.bin", "./tmp/main"]

FROM golang:1.26.2-alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app ./cmd/api

# Prod
FROM gcr.io/distroless/static:nonroot 
COPY --from=builder /app /app
ENTRYPOINT ["/app"]