apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: ruscan
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
    - port: 8080
      path: /metrics
      interval: 15s