apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
  namespace: ruscan
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/chivta/ruscan/frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: app-secrets
      imagePullSecrets:
      - name: ghcr-secret