apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper
  namespace: ruscan
  labels:
    app: scraper
spec:
  schedule: "0 3 * * 0" # Every Sunday at 3 AM
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: scraper
        spec:
          containers:
            - name: scraper
              image: ghcr.io/chivta/ruscan/scraper:placeholder
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 256Mi
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets
                      key: DATABASE_URL
                - name: LastFMAPIKey
                  valueFrom:
                    secretKeyRef:
                      name: app-secrets
                      key: LastFMAPIKey
                - name: ScrapeLastFMTopArtistsForAllTags
                  value: "true"
                - name: ScrapePhonkersDBArtists
                  value: "true"
                - name: ScrapeMusicBrainzArtistsForAllRegions
                  value: "true"


          restartPolicy: OnFailure