// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/scan_job.proto

package queue

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceType int32

const (
	ResourceType_INVALID     ResourceType = 0
	ResourceType_PLAYLIST_ID ResourceType = 1
	ResourceType_TRACK_ID    ResourceType = 2
	ResourceType_ALBUM_ID    ResourceType = 3
	ResourceType_ARTIST_ID   ResourceType = 4
	ResourceType_ARTIST_NAME ResourceType = 5
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "INVALID",
		1: "PLAYLIST_ID",
		2: "TRACK_ID",
		3: "ALBUM_ID",
		4: "ARTIST_ID",
		5: "ARTIST_NAME",
	}
	ResourceType_value = map[string]int32{
		"INVALID":     0,
		"PLAYLIST_ID": 1,
		"TRACK_ID":    2,
		"ALBUM_ID":    3,
		"ARTIST_ID":   4,
		"ARTIST_NAME": 5,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scan_job_proto_enumTypes[0].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_proto_scan_job_proto_enumTypes[0]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{0}
}

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_SPOTIFY              Provider = 1
	Provider_YOUTUBE              Provider = 2
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "SPOTIFY",
		2: "YOUTUBE",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"SPOTIFY":              1,
		"YOUTUBE":              2,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scan_job_proto_enumTypes[1].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_proto_scan_job_proto_enumTypes[1]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{1}
}

type ScanJob struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceType       ResourceType           `protobuf:"varint,2,opt,name=resource_type,json=resourceType,proto3,enum=ruscan.ResourceType" json:"resource_type,omitempty"`
	ResourceIdentifier string                 `protobuf:"bytes,3,opt,name=resource_identifier,json=resourceIdentifier,proto3" json:"resource_identifier,omitempty"`
	Provider           Provider               `protobuf:"varint,4,opt,name=provider,proto3,enum=ruscan.Provider" json:"provider,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ScanJob) Reset() {
	*x = ScanJob{}
	mi := &file_proto_scan_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanJob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanJob) ProtoMessage() {}

func (x *ScanJob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scan_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanJob.ProtoReflect.Descriptor instead.
func (*ScanJob) Descriptor() ([]byte, []int) {
	return file_proto_scan_job_proto_rawDescGZIP(), []int{0}
}

func (x *ScanJob) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ScanJob) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_INVALID
}

func (x *ScanJob) GetResourceIdentifier() string {
	if x != nil {
		return x.ResourceIdentifier
	}
	return ""
}

func (x *ScanJob) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

var File_proto_scan_job_proto protoreflect.FileDescriptor

const file_proto_scan_job_proto_rawDesc = "" +
	"\n" +
	"\x14proto/scan_job.proto\x12\x06ruscan\"\xbc\x01\n" +
	"\aScanJob\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x129\n" +
	"\rresource_type\x18\x02 \x01(\x0e2\x14.ruscan.ResourceTypeR\fresourceType\x12/\n" +
	"\x13resource_identifier\x18\x03 \x01(\tR\x12resourceIdentifier\x12,\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x10.ruscan.ProviderR\bprovider*h\n" +
	"\fResourceType\x12\v\n" +
	"\aINVALID\x10\x00\x12\x0f\n" +
	"\vPLAYLIST_ID\x10\x01\x12\f\n" +
	"\bTRACK_ID\x10\x02\x12\f\n" +
	"\bALBUM_ID\x10\x03\x12\r\n" +
	"\tARTIST_ID\x10\x04\x12\x0f\n" +
	"\vARTIST_NAME\x10\x05*>\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSPOTIFY\x10\x01\x12\v\n" +
	"\aYOUTUBE\x10\x02B+Z)github.com/youruser/ruscan/internal/queueb\x06proto3"

var (
	file_proto_scan_job_proto_rawDescOnce sync.Once
	file_proto_scan_job_proto_rawDescData []byte
)

func file_proto_scan_job_proto_rawDescGZIP() []byte {
	file_proto_scan_job_proto_rawDescOnce.Do(func() {
		file_proto_scan_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scan_job_proto_rawDesc), len(file_proto_scan_job_proto_rawDesc)))
	})
	return file_proto_scan_job_proto_rawDescData
}

var file_proto_scan_job_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_scan_job_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_scan_job_proto_goTypes = []any{
	(ResourceType)(0), // 0: ruscan.ResourceType
	(Provider)(0),     // 1: ruscan.Provider
	(*ScanJob)(nil),   // 2: ruscan.ScanJob
}
var file_proto_scan_job_proto_depIdxs = []int32{
	0, // 0: ruscan.ScanJob.resource_type:type_name -> ruscan.ResourceType
	1, // 1: ruscan.ScanJob.provider:type_name -> ruscan.Provider
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scan_job_proto_init() }
func file_proto_scan_job_proto_init() {
	if File_proto_scan_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scan_job_proto_rawDesc), len(file_proto_scan_job_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_scan_job_proto_goTypes,
		DependencyIndexes: file_proto_scan_job_proto_depIdxs,
		EnumInfos:         file_proto_scan_job_proto_enumTypes,
		MessageInfos:      file_proto_scan_job_proto_msgTypes,
	}.Build()
	File_proto_scan_job_proto = out.File
	file_proto_scan_job_proto_goTypes = nil
	file_proto_scan_job_proto_depIdxs = nil
}
