apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- api/deployment.yaml
- api/service.yaml
- api/service-monitor.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- scan-worker/deployment.yaml
- scan-worker/service.yaml
- scan-worker/service-monitor.yaml
- scraper/cronjob.yaml
- spotify-gateway/deployment.yaml
- spotify-gateway/service.yaml
- spotify-gateway/service-monitor.yaml
- rabbitmq/statefulset.yaml
- rabbitmq/service.yaml
- redis/statefulset.yaml
- redis/service.yaml
- postgres/statefulset.yaml
- postgres/service.yaml
- ingress.yaml
- secrets.enc.yaml

images:
- name: ghcr.io/chivta/ruscan/api
  newName: ghcr.io/chivta/ruscan/api
  newTag: b3d0221a61dabd64ba3a63a1b544910e9b56730a
- name: ghcr.io/chivta/ruscan/frontend
  newName: ghcr.io/chivta/ruscan/frontend
  newTag: 9c21d275b6a81d6998bd8f268b14553b8f52eedc
- name: ghcr.io/chivta/ruscan/scan-worker
  newName: ghcr.io/chivta/ruscan/scan-worker
  newTag: b3d0221a61dabd64ba3a63a1b544910e9b56730a
- name: ghcr.io/chivta/ruscan/scraper
  newName: ghcr.io/chivta/ruscan/scraper
  newTag: b3d0221a61dabd64ba3a63a1b544910e9b56730a
- name: ghcr.io/chivta/ruscan/spotify-gateway
  newName: ghcr.io/chivta/ruscan/spotify-gateway
  newTag: b3d0221a61dabd64ba3a63a1b544910e9b56730a
