apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yml
- backend/configmap.yml
- frontend/deployment.yml
- postgres/statefulset.yml
- redis/deployment.yml
- ingress.yml
images:
- name: ghcr.io/chivta/spotiscan/spotiscan-backend
  newTag: f6bdf4155b34ec5511faa5463e72bb7c16debc96
- name: ghcr.io/chivta/spotiscan/spotiscan-frontend
  newTag: f6bdf4155b34ec5511faa5463e72bb7c16debc96
