apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend/deployment.yaml
- backend/service-monitor.yaml
- frontend/deployment.yaml
- scraper/cronjob.yaml
- postgres/statefulset.yaml
- redis/deployment.yaml
- ingress.yaml
images:
- name: ghcr.io/chivta/spotiscan/spotiscan-backend
  newName: ghcr.io/chivta/spotiscan/spotiscan-backend
  newTag: 56f03c030799d6342ec0b2d9a77d74d7f50b1c15
- name: ghcr.io/chivta/spotiscan/spotiscan-frontend
  newName: ghcr.io/chivta/spotiscan/spotiscan-frontend
  newTag: 9612514912f25e70e3c3ed741ff52af96eb94c27
- name: ghcr.io/chivta/spotiscan/spotiscan-scraper
  newName: ghcr.io/chivta/spotiscan/spotiscan-scraper
  newTag: 56f03c030799d6342ec0b2d9a77d74d7f50b1c15
