apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: ruscan
stringData:
    #ENC[AES256_GCM,data:yqibg30zT1G9TqR9dJSYqXDDuO+2831o3KYEIxI1bblgcBphmUfpqRY8FEUv6xLyMOh7j9ZX,iv:7QmnxNDwmmr7ho4aoVPSVTorhFTzVDTdNkM+HaF0tBE=,tag:0V2pvg3so3cPCeXMjK9ZQQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:dbID4AZGZyuLd4P5Udeuay092kmuCWFVgNq9UXsgTgvpDjAI+g1LezOGeWF0HGM+xoLS7EGamBHaiy6zYDKm0w==,iv:tsvKcg/vKUArYsu+HclduZmoFrW7hGTaH7ixYwAdVHk=,tag:CtCeWEJYxZBeCMGuY1LrdA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:UAnbpXyUM4Lw1qpO4faDNbjF9BtAInIJhVL1f6Qm7Tl2STH1ufetoX0YuRe63XlMRjpV67IEmsQcmqEIBhk4Dd0VqpX32IE=,iv:aXOE8cZ6o9UBaZYu40RITZZXe1E1kewez7rM85pzPEo=,tag:zQh2e7QFqjabyyLkt9DQGg==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:bk5J4BMxUWp3+Exg,iv:OxPm0aY9Dm/xFQhnW/tiPv9sObgzSYUyjWj8XkFPDIY=,tag:mZ1aCSX3OPY5tgFamzC3vA==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:EiJfXVz+9ajf5CEnjNhNQZDEW+mBXg==,iv:7Cn4SSoqLh5XWZmA77qpMspUziuDDWchDZisClxFNn4=,tag:FAUDJEKxN5KJ6PF8vLMMmQ==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:+oYARYJlvm0SNTGV6hhGe2gpFRDmUJcLRjJewnheUwUI953DK9x6TXJ6Ibn1,iv:/H8453aK+ZGjQyS0XMqBsq3rsCR9xDOtBZ6knhKKDxs=,tag:ZsIHjkay1jl+dgebvS35/Q==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:O4HirtsQ4e+hYKZi,iv:FKuWxb6W20ge5OWagR2I94q1b0Hj0jxnqNpKc2B7Erw=,tag:yo6Zoer0bv/sPAGipTSoyQ==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:5TXCaZIRNzDU08j02pfadK5PYA78GnW15sZlN/rgUAs=,iv:kyiVp1mGuNnZGUogdygxjtZEU/hhCYchVK3PISN/xZw=,tag:QBGglVqFiY/b2DrQRYui8A==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:bL/5zJwElXnxkpX9fhZQpCfM0Kx7aCbbsLBnI2qcbtg=,iv:EQ2F6FmxeYNn5CtDfyydAKBaELAIW5L9GJ8l3OWrRmY=,tag:s4a9pDDHD4uUq13+DBlj/w==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:0gsrFun8puGYZLDWEYkS/gnDlslessQHkjyjGqn4kYA=,iv:NdWAAPbEjawyIjrxeJ48NX0c9rJK42K6lgiNrtpNr+I=,tag:DlXMgBXS+xg3LGMlp52bUw==,type:str]
    LASTFM_SHARED_SECRET: ENC[AES256_GCM,data:swbJUDHU5h2NqNzIqcFDQFwgtpt6dJ72bdn/qlW9RRE=,iv:thh6+HeDwELHf1lRrhydTo5xYDzwP/rDAMIeoCjebo8=,tag:Rn50hT5HT3Sf3ccl0ypWrQ==,type:str]
    MUSICBRAINZ_CLIENT_ID: ENC[AES256_GCM,data:JPuczhDua1eQTOVer0EAepieqhZM0f1Ds55tQ60g9iA=,iv:wGSLKIxX5aMBVDReuufy4iWOyHaQSU11wP9QdZa16gI=,tag:PGOT32Df185/ftBdrbjakQ==,type:str]
    MUSICBRAINZ_CLIENT_SECRET: ENC[AES256_GCM,data:Cw2ZsYZe6wWUwv2xfabLfWaGNeimkMJL8DDxGDnY98Y=,iv:E9arlq8BuyXmh4D4BSkL8hSjHhaRV+OXyNgRiKEKyoE=,tag:OAmeLYWQUCc69ZjwEi2A9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTks0SmliejNCRHdUVHZZ
            eHQzdFNPTGw2TWF2SzFoU2l3eTJyR3QwUjFvCjlyQVFJZXlxQVNCZkRoOHI4eVYw
            ci9VWnpCSXdvWVJIa1pvYWdUQ1FyeFkKLS0tIHFIMGVxNlMvclF2RGUzZ25wR3Iv
            KzhOdEdpdVViYVNRTGZtVjdGNDdTTHcKc+x6lqK6+CJhaUplFCPGAg5GgZ//lsIK
            ueBfm65HgeP6RfGJhkQ14Sw7GsjU60HkFN7y8EWOWW9jcYKF8XhX/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T15:31:22Z"
    mac: ENC[AES256_GCM,data:f+X2ykhk0K6Ik/V8vg0Bc6sT9LxZNcgh7mkP9xXlluc8C9KW2JeEwpp2fXWotimyb/DbO0rxf+3bMib4cVBOqxWdknYRhSv3yp0UHPl0CLrvdIxj8u3DrJVake2o07gAmhRMZ+GLCgulFqSPPnkejnvP8mN1CO+R2bdY9xNHglw=,iv:qHk+dLxve4BfhB3eP+OewHpYQ8WP5wuCAKDb/YDSaYo=,tag:46Dk12VS+KL7iS+70Fl2cw==,type:str]
    version: 3.13.0
---
apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ruscan
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:6h7YSF90jimWtkJgOSczH1AMWUApHBxFmDWDkK2j8lJDYS6ctoB2KKIEFnFAyjdcLvz6WC4Otst9HvpqrgZp4XrCklFtGnk/hE3gAP9kVkgLcM3ySu/SxynaHc6VSVI5cMZHynyRrR9Gmea+JutP08wiI2YcVNVgKmomalUeBqxIChWye74EHPplmXqDP8tBSUcxXNQMpPxLJMJ9/8qe3VdsM1zeeb/bq8WBBs1gATZrNZE76F0b+n7H4ICsWqauwx3pclcJ2edP+8o/N6hOTgmVUt5ryA==,iv:s+8HFDifCyacvZWWfvKLliQ+ZQMfqCrvTKti2QCHYTc=,tag:7Uav1SxuOlylDkN/sB5zcg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTks0SmliejNCRHdUVHZZ
            eHQzdFNPTGw2TWF2SzFoU2l3eTJyR3QwUjFvCjlyQVFJZXlxQVNCZkRoOHI4eVYw
            ci9VWnpCSXdvWVJIa1pvYWdUQ1FyeFkKLS0tIHFIMGVxNlMvclF2RGUzZ25wR3Iv
            KzhOdEdpdVViYVNRTGZtVjdGNDdTTHcKc+x6lqK6+CJhaUplFCPGAg5GgZ//lsIK
            ueBfm65HgeP6RfGJhkQ14Sw7GsjU60HkFN7y8EWOWW9jcYKF8XhX/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T15:31:22Z"
    mac: ENC[AES256_GCM,data:f+X2ykhk0K6Ik/V8vg0Bc6sT9LxZNcgh7mkP9xXlluc8C9KW2JeEwpp2fXWotimyb/DbO0rxf+3bMib4cVBOqxWdknYRhSv3yp0UHPl0CLrvdIxj8u3DrJVake2o07gAmhRMZ+GLCgulFqSPPnkejnvP8mN1CO+R2bdY9xNHglw=,iv:qHk+dLxve4BfhB3eP+OewHpYQ8WP5wuCAKDb/YDSaYo=,tag:46Dk12VS+KL7iS+70Fl2cw==,type:str]
    version: 3.13.0
