apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: ruscan
stringData:
    #ENC[AES256_GCM,data:nmiiyJ1MeK9MiDyZ+vdA3hMYOSyZAhxv7IH6E2uFo2sUCb3l48SywpRMUhSypJS7UDi8uwEC,iv:Eyg3/h0eeA2SuXG8znUgRObVl8PPRDTQAn1GgF5Kj2I=,tag:cItVYnNjmuO9YyqVzOYkyQ==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:rRrZXf0NSQF7Y2EfoiqWZiuxCSBipPBwU8F0TC0P1d15oRmpXoeSo/qiygX9I5PfMIxkhYGyL/WYYkkksKlrAg==,iv:adaKLHqW3XEtgCFxvV8reJpa+t1V2DnU+AGyi2n4B/Y=,tag:tvts2MZjRp6u5IP2kBNqsQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:hk/FDcgSUAGFr6pmU2vRSKWtFf8v6wdTIepBIVpHDGoqBft+7zOmE5R6q6XBzsYItLWhK1lTV6TsFAUgRy33v/hs6Q==,iv:DTww4Ytgcs/5KjV+fyFY2IYxFr4n79q4u2JA8VE1oXw=,tag:+H98LYnByudlzgOdOfQZoQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:ykUttQVpukBGkm+x,iv:9EhRUkxn/WVWW4ReSikNL1Dw2VqsP4yJhz2JYd1HFQw=,tag:9UVUj9msXLOLhIxlv/Ui1A==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:PBNsUe/MERxGeQ82n1sb3rrv,iv:txM5Ab3Ig93sRu4+ReYXEj29xd3EIfzhqRv2bUOl+/M=,tag:Fb3mVL36xEhjJBAJvpLpLA==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:MC9p3/RIxE949eneGm1h/vgQIq5DXDjhpdBpwMBYtLodQb+xeTrzrJM=,iv:oBeEvDdSqet832MiHGymoBPV8aleHstxqXEZYzEeDeQ=,tag:N+U+eUsJBbQcp/1gx/4tmA==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:NzNb0ESICT/Zs7Ri,iv:AwcWW2XagMb2vrv+skxC2lp3IL2940e25A1RDwLsicc=,tag:ijgAh+xPEY7pDq5g7rhWVQ==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:UB3SFV1KjRidL5f8whX2B5Mshy2yL+UuZBRqu8g1AC8=,iv:ngAqkzxdgLrucXsdwnwnwpJBYGy/n5ibiewuzYnse3g=,tag:XrovFvvvZMZXD55BPd1tTQ==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:x7XvUJSP3j57dWd1NMwgqRBc2SCPoR/JMv3pjTUhbM4=,iv:AvT6BLKc/qVPzVwsPWU4zYyrJncy83WhZXxbRCSNQk8=,tag:Wh6PdtRtoHm2KjpT2leIUg==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:egoSz2uUP65S98bIzZ0gG+zzqXrrGnTMuqKa7wT1kgU=,iv:zWqaVTpMRnEPJhRec6yaB8B69pUO8huUpUvcfqBXCYM=,tag:WByvzc6CcN6x9XSdgG8SZg==,type:str]
    LASTFM_SHARED_SECRET: ENC[AES256_GCM,data:LIW47p8jw5ZEsniJtDz/lHueIXTbu9XXP+R1pL+2080=,iv:8+8AxwDbjKetGmMPa4FAQr9L+OrichHC3a65UEAw5h8=,tag:MrnnanxXsWi3BvPG+iHuAA==,type:str]
    MUSICBRAINZ_CLIENT_ID: ENC[AES256_GCM,data:z9JMIux4b8y1KZwg++81+kJd8UZJKlUBuIuPOEvus5E=,iv:oDXXRbxkGa35DEfLfMZWiLEizFzQJ1J/t+qAOaxQHxw=,tag:/tz2nhurOAizNR3YO1w/yQ==,type:str]
    MUSICBRAINZ_CLIENT_SECRET: ENC[AES256_GCM,data:xifFOIy4vmcpyHVDBXRay67chvwn0Uop+CQ5uLNk6jE=,iv:i1MPaisP277EcgT1UesFcotzIafm8gGzS61yDqTwNr0=,tag:U/cw6xc3DYwrIUkVPT5yYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNFcybEY4MTk3ZHh0ZTRk
            MHg1WnZIOVNOWjRQcGVLWndvVnA0UFQ4OUVvClVKdEd2ajNkUmljUFhaTHQrMnI5
            Z1Yzc3VTbnFqdGp6NkdoV1JWYVR0WVEKLS0tIFUxajRXVXVyZ0U3Si9TNWRvZTZM
            S3dab3AyaVQ5L21ac1plcEdpaVJRYncKVoW34ATsTx72jPU+Piyq+kyc6L14WWZB
            9NOTIXWXh65wS8E7YIlgrVajXYKfxWU4BiV0zvWZC2+MMdwMld8EEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T12:22:19Z"
    mac: ENC[AES256_GCM,data:sgKCwl2Yr4blKOXigfjbKGtWGyXlh0a0YBxNhqlhZ+esWLrDMhlDqXiyFRlM4d2dzSG1qONBG08SBG0hEDJj7nxgMEVRJ6n89qmOUdnGFlcHs2p99SWGX53tnjtjldfCecSToH1+Xqhb9hwZt0OIVO21BEBquvZofEmr7t869Vg=,iv:IAHZ47Ljh0D2w4+ZN2MvBkerliwC6tIV1IQaKDhoaMw=,tag:1JmA30wXN6BRSK9LeTZdbg==,type:str]
    version: 3.13.1
---
apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:H9oFHBXI7V5TvdF4C4jE+sJtOWiqYVjbbHBuAuzH/bnhUP1r2g/mctRTaPv5AGim0I4+tzvGNQ9sVmLvBy3xHlqcPqQSge/V7V2DD76BIvkI6gVIKvUa8rDZGw0fJAKsLdcywF69jBQ3XurPk6Gqeb/RAw72zxFprWNsXpea12rakEZLUwLBPHp7/BuWe8zfumWxjv8bXyHZHo0+7ldhFomM8KsJc3X0PnNTFScfk3/eRZKZ0tWKwMkbm34wfLlxalltZdKjzBD3wWvgeBDiKTwMWk+saxfJwNKJC2KwB5dYpsJAeQdhU71/V1OhCzNlmrlVdz3oaDStU5ytma55b/b0HFM7WJfVYSC3SA==,iv:cjZkCWuis6TSRuRVbOPMMPz3ww83x4uniLf4Qzb91RQ=,tag:KldTwdrp3/h4X0BiPORmag==,type:str]
kind: Secret
metadata:
    name: ghcr-secret
    namespace: ruscan
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNFcybEY4MTk3ZHh0ZTRk
            MHg1WnZIOVNOWjRQcGVLWndvVnA0UFQ4OUVvClVKdEd2ajNkUmljUFhaTHQrMnI5
            Z1Yzc3VTbnFqdGp6NkdoV1JWYVR0WVEKLS0tIFUxajRXVXVyZ0U3Si9TNWRvZTZM
            S3dab3AyaVQ5L21ac1plcEdpaVJRYncKVoW34ATsTx72jPU+Piyq+kyc6L14WWZB
            9NOTIXWXh65wS8E7YIlgrVajXYKfxWU4BiV0zvWZC2+MMdwMld8EEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-01T12:22:19Z"
    mac: ENC[AES256_GCM,data:sgKCwl2Yr4blKOXigfjbKGtWGyXlh0a0YBxNhqlhZ+esWLrDMhlDqXiyFRlM4d2dzSG1qONBG08SBG0hEDJj7nxgMEVRJ6n89qmOUdnGFlcHs2p99SWGX53tnjtjldfCecSToH1+Xqhb9hwZt0OIVO21BEBquvZofEmr7t869Vg=,iv:IAHZ47Ljh0D2w4+ZN2MvBkerliwC6tIV1IQaKDhoaMw=,tag:1JmA30wXN6BRSK9LeTZdbg==,type:str]
    version: 3.13.1
