apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: ruscan
stringData:
    #ENC[AES256_GCM,data:vNK0ji+kCCefBU9yBGCMoXr07U0NYmyXvrk1lSBcOAOVbDGyyjMi6tazxJotYCC09cxGaeSr,iv:+bNGtWNZ5Njgo6wD/ShzloFvCtU28EGZ49B6whuX9oQ=,tag:/5ZaTLMQ6qodHD1SkyOpTA==,type:comment]
    JWT_SECRET: ENC[AES256_GCM,data:osIm1Ag6fIJGZBx+iQtMvF0cNcooNOfgRiP13hE0BuyHTL61X5to+wYGISRxFoiwvBmbWb++UUfZ4NXwIgXb7g==,iv:seZ0lrrkFzUbYl8Cy61sWg+rOdnMO4/FCQGgBN8rQag=,tag:s0CUv+kGRJY2pXLUQHlSJg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ok/w6tATtGC02s5lSOX+ijNDIdkHEyXpaWH2ZckUyWCVjVLS+IydiqK4EAKVOZUi7TzdwDdWvl1QVuMGzEmqX4yvbCzrcuY=,iv:3hZdMxRy72ho8xLykgH21Z7LOFRZjcRQFjXPib9JeW8=,tag:KRQPD0awzbTcIZ/Zvw/17g==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:2WhMPQ3MunldNz3A,iv:WOMk+l014XvwkiwASW1yIHrBJGstZHHVDMw05y9JnHg=,tag:M//zIsoCQFvzyX25e+Yphw==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:8M8BFvLVSFL53rKAEpBhFJNjp26xnA==,iv:1dCNU+jA5vqj1vUZoBuhuFEdJFl/EsWVHOoqohHO7xE=,tag:lnZqVtiwGZqRBwJOBjN+2Q==,type:str]
    RABBITMQ_URL: ENC[AES256_GCM,data:ryda/sDRSEXXtsWJ5QAR7j5iwUcNXLgqqpE4DlUW6VvO+tEMhyTvasiW0nDw,iv:tWLU9tpGnVlPVxhWuQ42IFD6HLAkksXBw18UkCNQ5tM=,tag:epxxz7ueBroNS7mGkzYO/g==,type:str]
    RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:zt2RzRZIYUEvcRDu,iv:20ODbdIitvdhA+oYDg4TiVrK4hNJq47EKykSVI/phc8=,tag:OaYSfxeMVwfgKUKDNKG7XA==,type:str]
    SPOTIFY_CLIENT_ID: ENC[AES256_GCM,data:EHSDsVtyxKc8tSjrppd74PKEzKM2eZ/E8wvX4KFji+U=,iv:yW6sCqrIpG+6zf1sTwA0AaRDomRA7czUcHZy+VgJ7b8=,tag:4IIXCYOIb93/UQSZenTwSA==,type:str]
    SPOTIFY_CLIENT_SECRET: ENC[AES256_GCM,data:mNGL0NFRcNIcf+EZHA5orJekqINZjik9TgqeOdIJ6Tk=,iv:F5m2RJQqjzNCGLkkCbky6I2wf/XP4wuxGUq2uvTbp7A=,tag:Xaz3nk+YhRruiq+huOHrnA==,type:str]
    LASTFM_API_KEY: ENC[AES256_GCM,data:Z26Fue0dOnr9OHHFsl9P24Lkvli8uhaKjYwhteFuae0=,iv:EgXSQPx7fCy6kAYeN6GGRxnU1x5fF+bHhVhZRYq6PRs=,tag:liS913ZMeK1EiJc8EMPW+w==,type:str]
    LASTFM_SHARED_SECRET: ENC[AES256_GCM,data:YZaEztrCT5li4A2aDr+gOuw71u8pkyv625Yyi2kNy7Y=,iv:dCK4wj0kBiDE1uOf9Z9G3h8cotGlH2d3iGXNSl6chcw=,tag:jwOmwudMnkzNdfwaBzR45A==,type:str]
    MUSICBRAINZ_CLIENT_ID: ENC[AES256_GCM,data:MCOCdFeS+LMthGjfjQcs7WPYGQ5fJzDLd1yLrhKP1MI=,iv:it+EEVsbZurynhf7PZXtGnKAJj1S+YqQwypfz10yDLI=,tag:HFYQqEkHP+/ixuV0TggL7Q==,type:str]
    MUSICBRAINZ_CLIENT_SECRET: ENC[AES256_GCM,data:4aBoVTls/woGBG9SUA8CxAlYuSHdbFQno6L33MjQTY8=,iv:q+IGhC24ZZhX//cWLasGXqCBapr+ziqgjd7QodZ+PMw=,tag:6szcYdc6+t7dwd+7fuGeeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blR0Y2ZxS29IWHVweERE
            S2FjbTczckxYSE9MRTZVR3NLV1pOZkpKSHg0CkFqV1VLS3ZBWW5ZY3R1Tjk2ZUdH
            M2RrR2I4QklUQlgzQmhsYkRMcy93VVEKLS0tIEUzb01uaUZoWEs4d2YzN3k1UWpF
            aklRV1BnSlREak42ODNJcElNcVJBbVEK+nCnK3WM7aecywo4UH+quB+3WnyUBxh5
            rdHt/mPqB2/GfJBVO/8yVRS4rltrWUbhROPlgY9/0Vu7D+OGXS9AWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10d00xrpljw4cga37ad0gt7se4nsehp5uv8yy3grkfqygd4pzyffqj3gr46
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-11T15:40:14Z"
    mac: ENC[AES256_GCM,data:GQVi3eVTjua0O7K1PEZRxx2ll/lWbgonaT7zJUCHKUH+1Z9i5IxjFbhuwNL5nHr/3c8+OZKpmn+vBrNp4hPry0t64YZMhIH+vyDJCl8beRCtTTW2vx3hXJ/tZ8z5di3Cmjd8do2o862ILKVLx4mQzl77MXT1qSviJg0qEyWmVeo=,iv:/kqy/m4ipXgK7fVoXNfox2cf/iHtdO3YJbeWU2bNzpI=,tag:o1A2/YDxpLy/3laxJhPIWA==,type:str]
    version: 3.13.0
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiY2hpdnRhIiwicGFzc3dvcmQiOiJnaHBfajROV0syZDNSODc2YkN4b3pRaHJSbG9DZm1MckF6MDVDTnM2IiwiZW1haWwiOiJhcnZsYXM3OEBnbWFpbC5jb20iLCJhdXRoIjoiWTJocGRuUmhPbWRvY0Y5cU5FNVhTekprTTFJNE56WmlRM2h2ZWxGb2NsSnNiME5tYlV4eVFYb3dOVU5PY3pZPSJ9fX0=
kind: Secret
metadata:
  name: ghcr-secret
  namespace: ruscan
type: kubernetes.io/dockerconfigjson
