apiVersion: v1
kind: Service
metadata:
  name: spotify-gateway-svc
  namespace: ruscan
  labels:
    app: spotify-gateway
spec:
  selector:
    app: spotify-gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP