name: CI

on:
  # Do not run CI/CD on purely k8s changes
  # So github-actions[bot] won't trigger CD when it updates the kustomization.yaml with new tags
  push:
    branches: [main]
    paths-ignore:
      - 'k8s/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'k8s/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.2'
          cache: true
          cache-dependency-path: backend/go.sum
          
      - name: Download deps
        run: go mod download

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...
     
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build